
title: gloriously awkward life #Your awesome title
email: steven@gloriouslyawkwardlife.com #youremail@domain.com
description: > # this means to ignore newlines until "baseurl"
  Neurodivergent Christian 50-something with a Disney addiction.

baseurl: # the subpath of the site
url: http://gloriouslyawkwardlife.com # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

user:
  name: Steven Buehler
  pic: /assets/img/cat.jpg
  picAlt: "catbook"
  job: <em>gloriously</em> awkward.
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
